sudo: false
language: ruby
env:
  global:
    secure: "ZolLJeOZ3mokg3+pTbo1Uxq6Dt6rl3sz3kWNGIEsgGI0XvGMnl2vj5uDRbvJqkB8QZXTFTtfMXNcKpVWOEXZ/yARPl+vMSTHmwufHf2ztrzOfjrI/dAZZrd2QHbE4k96KX31oSGLYArSX8vY1PGQC+pgkjZjl/0Ddc2zIyy+Ffc="
script:
- echo $VERY_SECRET
