language: ruby
matrix:
  include:
  - sudo: required
    dist: trusty
    env: QUEUE=gce DIST=trusty
  - sudo: required
    dist: precise
    env: QUEUE=gce DIST=precise
  - sudo: false
    dist: trusty
    group: beta
    env: QUEUE=ec2 DIST=trusty
  - sudo: false
    dist: precise
    env: QUEUE=docker DIST=precise
  - os: osx
    rvm: default
    env: QUEUE=macstadium6 IMAGE=default
  - os: osx
    osx_image: xcode7
    rvm: default
    env: QUEUE=macstadium6 IMAGE=xcode7
script: git --version
